[workspace]
members = [
    "tracking",
    "antenna-controller",
    "ground-station",
    "framing",
    "demod",
    "telemetry",
    "packetizer",
    "mqtt-client",
    "api",
    "jobs",
]
resolver = "3"
