[workspace]
members = [
    "tracking",
    "hdlc",
    "antenna-controller",
    "ground-station",
    "framing",
    "demod", "cli",
    "telemetry",
    "packetizer", "mqtt-client",
]
resolver = "3"
