[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = "1.0.219"
serde_json = "1.0.143"
tracking = { path = "../tracking" }
