# RUSTAR Ground Station Configuration
# This file contains configuration parameters for the ground station software

[mqtt]
# MQTT broker configuration
host = "127.0.0.1" # MQTT broker hostname or IP address
# host = "test.mosquitto.org"
port = 8888 # MQTT broker port
# port = 1883
transport = "tls" # Transport type: "tcp" or "tls"
# transport = "tcp"
timeout_seconds = 30 # Connection timeout in seconds

[mqtt.auth]
# MQTT authentication credentials (optional - comment out for anonymous access)
username = ""
password = ""

[ground_station]
# Ground station identification
id = "GS-BUENOS-AIRES" # Unique identifier for this ground station

[ground_station.location]
# Geographic location
latitude = -34.6  # Latitude in degrees (negative for South)
longitude = -58.4 # Longitude in degrees (negative for West) 
altitude = 2.5    # Altitude in meters above sea level

[api]
# REST API server configuration
host = "127.0.0.1" # API server bind address
port = 9999        # API server port

[sdr]
# SDR configuration - choose one type:
# type = "mock"  # Synthetic test signal
type = "zmq_mock"
zmq_endpoint = "tcp://127.0.0.1:5556"
# type = "soapy"
# soapy_string = "driver=rtlsdr"

# Note: You can also override these values using environment variables:
# RUSTAR_MQTT_HOST=192.168.1.100
# RUSTAR_MQTT_PORT=1883
# RUSTAR_GROUND_STATION_LATITUDE=-34.123
# RUSTAR_API_HOST=0.0.0.0
# RUSTAR_API_PORT=8080
# etc.
