[package]
name = "packetizer"
version = "0.1.0"
edition = "2024"

[dependencies]
hdlc = { path = "../hdlc" }
telemetry = { path = "../telemetry" }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = "1.0.143"
