name: Rust CI

on:
    push:
        branches: ['**']
    pull_request:
        branches: ['**']

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install system dependencies
              run: sudo apt-get update && sudo apt-get install -y libudev-dev libzmq3-dev pkg-config
              
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install rustfmt
              run: rustup component add rustfmt

            - name: Install clippy
              run: rustup component add clippy

            - name: Check formatting
              run: cargo fmt --all -- --check

            - name: Build all packages
              run: cargo build --workspace --all-targets

            - name: Run clippy
              run: cargo clippy --all-targets --all-features -- -D warnings

            - name: Run tests
              run: cargo test --all --verbose
